# Generated by Django 3.2.6 on 2021-08-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='from_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_id',
        ),
    ]
