# Generated by Django 3.2.6 on 2021-08-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210807_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
